services:
  normanpd-pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./resources:/app/resources
    command: python main.py
    #ports:
    #  - 8000:8000
    environment:
      - LOG_LEVEL=INFO
      - .env
  
  volumes:
    - ./.cache:/app/.cache