services:
  normanpd-pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./resources:/app/resources
      - ./.cache:/app/.cache
    command: python -m src.pipeline.main
    env_file:
      - .env
    environment:
      - LOG_LEVEL=INFO